/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalc extends javax.swing.JFrame {
    //Variables restringidas - Privada
    private String entrada = "";
    private double n1, n2;
    private String op = "";
    /**
     * Creates new form jfrmCalc
     */
    public jfrmCalc() {
        initComponents();
        this.setTitle("Calculadora Avanzada");
        this.setSize(280, 370);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbt13 = new javax.swing.JButton();
        jbt14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jtfCantidad = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jbt7 = new javax.swing.JButton();
        jbt8 = new javax.swing.JButton();
        jbt9 = new javax.swing.JButton();
        jbtSuma = new javax.swing.JButton();
        jbt6 = new javax.swing.JButton();
        jbt4 = new javax.swing.JButton();
        jbt5 = new javax.swing.JButton();
        jbtResta = new javax.swing.JButton();
        jbt1 = new javax.swing.JButton();
        jbt2 = new javax.swing.JButton();
        jbt3 = new javax.swing.JButton();
        jbtMulti = new javax.swing.JButton();
        jbt0 = new javax.swing.JButton();
        jbtDecimal = new javax.swing.JButton();
        jbtRaiz = new javax.swing.JButton();
        jbtDivision = new javax.swing.JButton();
        jbtBorrar = new javax.swing.JButton();
        jbtBorrarindividual = new javax.swing.JButton();
        jbtPorcentaje = new javax.swing.JButton();
        jbtIgual = new javax.swing.JButton();

        jbt13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt13.setText("1");
        jbt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt13ActionPerformed(evt);
            }
        });

        jbt14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt14.setText("1");
        jbt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt14ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jPanel2.setBackground(new java.awt.Color(200, 242, 242));
        jPanel2.setLayout(new java.awt.GridLayout(5, 4));

        jPanel3.setBackground(new java.awt.Color(150, 242, 242));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jPanel4.setLayout(new java.awt.GridLayout(5, 4));

        jPanel6.setBackground(new java.awt.Color(156, 156, 156));

        jtfCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtfCantidad.setText("0");
        jtfCantidad.setEnabled(false);

        jPanel5.setBackground(new java.awt.Color(156, 156, 156));
        jPanel5.setLayout(new java.awt.GridLayout(5, 4));

        jbt7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt7.setText("7");
        jbt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt7ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt7);

        jbt8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt8.setText("8");
        jbt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt8ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt8);

        jbt9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt9.setText("9");
        jbt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt9ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt9);

        jbtSuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtSuma.setText("+");
        jbtSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSumaActionPerformed(evt);
            }
        });
        jPanel5.add(jbtSuma);

        jbt6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt6.setText("6");
        jbt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt6ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt6);

        jbt4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt4.setText("4");
        jbt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt4ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt4);

        jbt5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt5.setText("5");
        jbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt5ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt5);

        jbtResta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtResta.setText("-");
        jbtResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRestaActionPerformed(evt);
            }
        });
        jPanel5.add(jbtResta);

        jbt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt1.setText("1");
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt1);

        jbt2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt2.setText("2");
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt2);

        jbt3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt3.setText("3");
        jbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt3ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt3);

        jbtMulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtMulti.setText("x");
        jbtMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiActionPerformed(evt);
            }
        });
        jPanel5.add(jbtMulti);

        jbt0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbt0.setText("0");
        jbt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt0ActionPerformed(evt);
            }
        });
        jPanel5.add(jbt0);

        jbtDecimal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtDecimal.setText(".");
        jbtDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDecimalActionPerformed(evt);
            }
        });
        jPanel5.add(jbtDecimal);

        jbtRaiz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtRaiz.setText("√");
        jbtRaiz.setToolTipText("");
        jbtRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRaizActionPerformed(evt);
            }
        });
        jPanel5.add(jbtRaiz);

        jbtDivision.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtDivision.setText("/");
        jbtDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivisionActionPerformed(evt);
            }
        });
        jPanel5.add(jbtDivision);

        jbtBorrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtBorrar.setText("AC");
        jbtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBorrarActionPerformed(evt);
            }
        });
        jPanel5.add(jbtBorrar);

        jbtBorrarindividual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtBorrarindividual.setText("C");
        jbtBorrarindividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBorrarindividualActionPerformed(evt);
            }
        });
        jPanel5.add(jbtBorrarindividual);

        jbtPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtPorcentaje.setText("%");
        jbtPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPorcentajeActionPerformed(evt);
            }
        });
        jPanel5.add(jbtPorcentaje);

        jbtIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtIgual.setText("=");
        jbtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIgualActionPerformed(evt);
            }
        });
        jPanel5.add(jbtIgual);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(720, 720, 720)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt7ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 7;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt7ActionPerformed

    private void jbt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt8ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 8;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt8ActionPerformed

    private void jbt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt9ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 9;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt9ActionPerformed

    private void jbt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt0ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 0;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt0ActionPerformed

    private void jbt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt4ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 4;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt4ActionPerformed

    private void jbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt5ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 5;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt5ActionPerformed

    private void jbt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt6ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 6;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt6ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 1;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 2;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt2ActionPerformed

    private void jbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt3ActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 3;
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbt3ActionPerformed

    private void jbtSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSumaActionPerformed
        // TODO add your handling code here:
        n2 = Double.parseDouble(entrada);
        entrada = "";
           
        if (op.equals("+")){
            n1 = n1 + n2;
        }
        else if (op.equals("-")){
            n1 = n1 - n2;
        }
        else if (op.equals("x")){
            n1 = n1 * n2;
        }
        else if (op.equals("/")){
            n1 = n1 / n2;
        }
        else{
            n1 = n2;
        }

        op = "+";
        jtfCantidad.setText(""+n1);
    }//GEN-LAST:event_jbtSumaActionPerformed

    private void jbtRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRestaActionPerformed
        // TODO add your handling code here:
        n2 = Double.parseDouble(entrada);
        entrada = "";
           
        if (op.equals("+")){
            n1 = n1 + n2;
        }
        else if (op.equals("-")){
            n1 = n1 - n2;
        }
        else if (op.equals("x")){
            n1 = n1 * n2;
        }
        else if (op.equals("/")){
            n1 = n1 / n2;
        }
        else{
            n1 = n2;
        }

        op = "-";
        jtfCantidad.setText(""+n1);
    }//GEN-LAST:event_jbtRestaActionPerformed

    private void jbtMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiActionPerformed
        // TODO add your handling code here:
        n2 = Double.parseDouble(entrada);
        entrada = "";
           
        if (op.equals("+")){
            n1 = n1 + n2;
        }
        else if (op.equals("-")){
            n1 = n1 - n2;
        }
        else if (op.equals("x")){
            n1 = n1 * n2;
        }
        else if (op.equals("/")){
            n1 = n1 / n2;
        }
        else{
            n1 = n2;
        }

        op = "x";
        jtfCantidad.setText(""+n1);
    }//GEN-LAST:event_jbtMultiActionPerformed

    private void jbtDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivisionActionPerformed
        // TODO add your handling code here:
        n2 = Double.parseDouble(entrada);
        entrada = "";
           
        if (op.equals("+")){
            n1 = n1 + n2;
        }
        else if (op.equals("-")){
            n1 = n1 - n2;
        }
        else if (op.equals("x")){
            n1 = n1 * n2;
        }
        else if (op.equals("/")){
            n1 = n1 / n2;
        }
        else{
            n1 = n2;
        }

        op = "/";
        jtfCantidad.setText(""+n1);
    }//GEN-LAST:event_jbtDivisionActionPerformed

    private void jbtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIgualActionPerformed
        // TODO add your handling code here:
        double resultado;

        n2 = Double.parseDouble(entrada);

        if (op.equals("+")){
            resultado = n1 + n2;
        }
        else if (op.equals("-")){
            resultado = n1 - n2;
        }
        else if (op.equals("x")){
            resultado = n1 * n2;
        }
        else if (op.equals("/")){
            resultado = n1 / n2;
        }
        else{
            resultado = n2;
        }

        entrada = String.valueOf(resultado);
        jtfCantidad.setText(entrada);

        n1 = resultado;
        op = "";
    }//GEN-LAST:event_jbtIgualActionPerformed

    private void jbtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBorrarActionPerformed
        // TODO add your handling code here:
        entrada = "0";
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbtBorrarActionPerformed

    private void jbtDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDecimalActionPerformed
        // TODO add your handling code here:
        if (!entrada.contains(".")){
        if (entrada.equals("")){
            entrada = "0.";
        } else {
            entrada = entrada + ".";
        }
        jtfCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtDecimalActionPerformed

    private void jbtPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPorcentajeActionPerformed
        // TODO add your handling code here:
        if (entrada.equals("")){
            entrada = "0";
        }

        double num = Double.parseDouble(entrada);

        num = num / 100;

        entrada = String.valueOf(num);
        jtfCantidad.setText(entrada);
    }//GEN-LAST:event_jbtPorcentajeActionPerformed

    private void jbtRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRaizActionPerformed
        // TODO add your handling code here:
        if (entrada.equals("")){
            entrada = "0";
        }

        double num = Double.parseDouble(entrada);

        if (num >= 0){
            num = Math.sqrt(num);
            entrada = String.valueOf(num);
            jtfCantidad.setText(entrada);
        }
        else{
            jtfCantidad.setText("Error");
            entrada = "";
        }
    }//GEN-LAST:event_jbtRaizActionPerformed

    private void jbt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt13ActionPerformed

    private void jbt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt14ActionPerformed

    private void jbtBorrarindividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBorrarindividualActionPerformed
        // TODO add your handling code here:
        String texto = jtfCantidad.getText();

        if (texto.length() > 1) {
            texto = texto.substring(0, texto.length() - 1);
            jtfCantidad.setText(texto);
            entrada = texto;
        } else {
            jtfCantidad.setText("0");
            entrada = "0";
        }
    }//GEN-LAST:event_jbtBorrarindividualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbt0;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt13;
    private javax.swing.JButton jbt14;
    private javax.swing.JButton jbt2;
    private javax.swing.JButton jbt3;
    private javax.swing.JButton jbt4;
    private javax.swing.JButton jbt5;
    private javax.swing.JButton jbt6;
    private javax.swing.JButton jbt7;
    private javax.swing.JButton jbt8;
    private javax.swing.JButton jbt9;
    private javax.swing.JButton jbtBorrar;
    private javax.swing.JButton jbtBorrarindividual;
    private javax.swing.JButton jbtDecimal;
    private javax.swing.JButton jbtDivision;
    private javax.swing.JButton jbtIgual;
    private javax.swing.JButton jbtMulti;
    private javax.swing.JButton jbtPorcentaje;
    private javax.swing.JButton jbtRaiz;
    private javax.swing.JButton jbtResta;
    private javax.swing.JButton jbtSuma;
    private javax.swing.JTextField jtfCantidad;
    // End of variables declaration//GEN-END:variables
}
